//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.16 at 09:26:54 AM MSK 
//


package ru.usb.email;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.usb.email package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RequestBodyElementFileName_QNAME = new QName("", "fileName");
    private final static QName _RequestBodyElementBodyText_QNAME = new QName("", "bodyText");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.usb.email
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link Request.Attachments }
     * 
     */
    public Request.Attachments createRequestAttachments() {
        return new Request.Attachments();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link Request.BodyElement }
     * 
     */
    public Request.BodyElement createRequestBodyElement() {
        return new Request.BodyElement();
    }

    /**
     * Create an instance of {@link Request.Attachments.Attachment }
     * 
     */
    public Request.Attachments.Attachment createRequestAttachmentsAttachment() {
        return new Request.Attachments.Attachment();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fileName", scope = Request.BodyElement.class)
    public JAXBElement<String> createRequestBodyElementFileName(String value) {
        return new JAXBElement<String>(_RequestBodyElementFileName_QNAME, String.class, Request.BodyElement.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bodyText", scope = Request.BodyElement.class)
    public JAXBElement<String> createRequestBodyElementBodyText(String value) {
        return new JAXBElement<String>(_RequestBodyElementBodyText_QNAME, String.class, Request.BodyElement.class, value);
    }

}
