//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.16 at 09:22:44 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.tibco.com/schemas/Messages_GW/Schema.xsd2")
package massagegwmsb.output;
