//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.16 at 09:22:54 AM MSK 
//


package massagegwmsb.input;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the massagegwmsb.input package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: massagegwmsb.input
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Root }
     * 
     */
    public Root createRoot() {
        return new Root();
    }

    /**
     * Create an instance of {@link Root.MSG }
     * 
     */
    public Root.MSG createRootMSG() {
        return new Root.MSG();
    }

    /**
     * Create an instance of {@link Root.MSG.ViberMsg }
     * 
     */
    public Root.MSG.ViberMsg createRootMSGViberMsg() {
        return new Root.MSG.ViberMsg();
    }

    /**
     * Create an instance of {@link Root.MSG.PushMsg }
     * 
     */
    public Root.MSG.PushMsg createRootMSGPushMsg() {
        return new Root.MSG.PushMsg();
    }

    /**
     * Create an instance of {@link Main }
     * 
     */
    public Main createMain() {
        return new Main();
    }

    /**
     * Create an instance of {@link Root.MSG.LentaMsg }
     * 
     */
    public Root.MSG.LentaMsg createRootMSGLentaMsg() {
        return new Root.MSG.LentaMsg();
    }

    /**
     * Create an instance of {@link Root.MSG.SmsMsg }
     * 
     */
    public Root.MSG.SmsMsg createRootMSGSmsMsg() {
        return new Root.MSG.SmsMsg();
    }

    /**
     * Create an instance of {@link Root.MSG.ViberMsg.Content }
     * 
     */
    public Root.MSG.ViberMsg.Content createRootMSGViberMsgContent() {
        return new Root.MSG.ViberMsg.Content();
    }

    /**
     * Create an instance of {@link Root.MSG.PushMsg.Data }
     * 
     */
    public Root.MSG.PushMsg.Data createRootMSGPushMsgData() {
        return new Root.MSG.PushMsg.Data();
    }

}
