//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.16 at 09:22:17 AM MSK 
//


package massagegwmsb.status;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the massagegwmsb.status package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: massagegwmsb.status
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Root }
     * 
     */
    public Root createRoot() {
        return new Root();
    }

    /**
     * Create an instance of {@link Root.StatusMsg }
     * 
     */
    public Root.StatusMsg createRootStatusMsg() {
        return new Root.StatusMsg();
    }

    /**
     * Create an instance of {@link Root.StatusMsg.Multistatus }
     * 
     */
    public Root.StatusMsg.Multistatus createRootStatusMsgMultistatus() {
        return new Root.StatusMsg.Multistatus();
    }

    /**
     * Create an instance of {@link Root.StatusMsg.Multideliver }
     * 
     */
    public Root.StatusMsg.Multideliver createRootStatusMsgMultideliver() {
        return new Root.StatusMsg.Multideliver();
    }

    /**
     * Create an instance of {@link Root.StatusMsg.Multistatus.Lenta }
     * 
     */
    public Root.StatusMsg.Multistatus.Lenta createRootStatusMsgMultistatusLenta() {
        return new Root.StatusMsg.Multistatus.Lenta();
    }

    /**
     * Create an instance of {@link Root.StatusMsg.Multistatus.Push }
     * 
     */
    public Root.StatusMsg.Multistatus.Push createRootStatusMsgMultistatusPush() {
        return new Root.StatusMsg.Multistatus.Push();
    }

    /**
     * Create an instance of {@link Root.StatusMsg.Multistatus.Sms }
     * 
     */
    public Root.StatusMsg.Multistatus.Sms createRootStatusMsgMultistatusSms() {
        return new Root.StatusMsg.Multistatus.Sms();
    }

    /**
     * Create an instance of {@link Root.StatusMsg.Multistatus.Viber }
     * 
     */
    public Root.StatusMsg.Multistatus.Viber createRootStatusMsgMultistatusViber() {
        return new Root.StatusMsg.Multistatus.Viber();
    }

}
